name: climatex
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  dynamic_color: ^1.6.5
  flutter:
    sdk: flutter
  flutter_animate: ^4.1.1+1
  free_place_search: ^1.0.4
  geolocator: ^9.0.2
  google_nav_bar: ^5.0.6
  home_widget: ^0.2.1
  http: ^0.13.5
  intl: ^0.18.1
  lottie: ^2.3.2
  sleek_circular_slider: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/homeicon/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/Poppins/tellural alt.ttf
   